### ISSUE TITLE
Enable embeds in mdx

### ISSUE THREAD

**Issue by maxscience** [PaulieScanlon/gatsby-theme-gatstats#23]
As per https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-mdx#shortcodes 
it's possible to enable shortcodes to embed Youtube and Twitter inside .mdx (posts and pages).

Also other remark plugins can be made compatible with mdx (useful for embeds from other providers and other features):
https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-mdx#gatsby-remark-plugins

**Comment by PaulieScanlon** [comment]
@maxscience this sounds like a reasonable request. I'll add it to the features list

**Comment by PaulieScanlon** [comment]
Hey @maxscience i've just release 0.0.35 which supports .md files... With this update you can probably add your required embed plugins to your site, i think it'll just be a case of adding them to your `gatsby-config.js` That might get you out of a pickle in the short term and i'll try and put some time aside to investigate a built in option.

**Comment by maxscience** [comment]
.md files will keep working with the frontmatter template for metrics etc?
Thanks

**Comment by PaulieScanlon** [comment]
@maxscience Yeap should all still work as before

**Comment by maxscience** [comment]
@PaulieScanlon I just tried with both

- https://www.gatsbyjs.org/packages/@raae/gatsby-remark-oembed/
- https://www.gatsbyjs.org/packages/gatsby-remark-embedder

(installed one at a time) but they still won't properly render the embed in .md files.
I guess it's easier to just integrate the embeds in mdx as gatsby-plugin-mdx already has the feature

**Comment by PaulieScanlon** [comment]
@maxscience ok, i'll investigate thanks for trying

**Comment by PaulieScanlon** [comment]
@maxscience until the Oembed plugin works with `.mdx` i don't think there's much i can do. [#66](https://github.com/raae/gatsby-remark-oembed/issues/66)

**Comment by maxscience** [comment]
@PaulieScanlon What about this solution? https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-mdx#shortcodes

**Comment by PaulieScanlon** [comment]
@maxscience yeah that’s kinda how I’m handling the code snippets. I’ll have a think about it but I’m still conscious of adding a load of stuff to the theme that might not be required and thus causing bloat. I’m thinking perhaps a better solution would be if I wrote a separate mdx plugin to handle all of that bit I think it’s being investigated elsewhere 

https://github.com/raae/gatsby-remark-oembed/issues/66

https://github.com/raae/gatsby-remark-oembed/pull/88

**Comment by maxscience** [comment]
@PaulieScanlon ok although YouTube and twitter embeds are useful for any blog these days. For other services I agree a plugin might be a better idea

**Comment by PaulieScanlon** [comment]
@maxscience do you fancy beta testing `0.0.49` I've added YouTube and Tweet embeds _only_

**post**
https://gatsby-theme-gatstats.netlify.com/posts/2019/12/embed-example/

**src**
https://raw.githubusercontent.com/PaulieScanlon/gatsby-theme-gatstats/master/demo/src/posts/2019/12/embed-example.mdx

**Comment by maxscience** [comment]
@PaulieScanlon awesome it looks like it works well

**Comment by raae** [comment]
A fix for mdx support is merged and a new package will be released shortly: https://github.com/raae/gatsby-remark-oembed/issues/66#issuecomment-569726956

**Comment by PaulieScanlon** [comment]
@raae great work!
