### ISSUE TITLE
Advanced frontmatter template

### ISSUE THREAD

**Issue by maxscience** [PaulieScanlon/gatsby-theme-gatstats#26]
Useful tags would be:

- 'dateUpdated', so that it's possible to revise/update a post and still display the original publish date alongside the updated one
- 'status', can get values like 'published' and 'draft'. While status is draft, we can still write and save on git a draft of the post/page but it won't get built during gatsby build. Particularly useful for common CI/CD environments

**Comment by PaulieScanlon** [comment]
@maxscience yeah, i like both of those ideas. I'm not sure if by setting it to draft it would be excluded from the build but i can certainly make it so when its set to draft the post wouldn't appear in the posts list. Might have to work out how to excluded it from the data metrics as well though.

**Comment by PaulieScanlon** [comment]
Hey @maxscience i've implemented a `status` property in release `0.0.54` if you set 
`status: "draft"` in the frontmatter of any post it will be hidden from the site. The metrics collected to populate the charts also ignore any file with this status. Perhaps you open a new issue for the `dataUpdated` property if you still require it?

**Comment by maxscience** [comment]
@PaulieScanlon awesome although ideally draft posts would still be visible when doing gatsby develop for preview reasons.

**Comment by PaulieScanlon** [comment]
That sounds like a nice idea but I think the theme would need to be aware of dev / prof environments which would complicate setup for users so I probably won’t implement this
