### ISSUE TITLE
Newsletter option

### ISSUE THREAD

**Issue by maxscience** [PaulieScanlon/gatsby-theme-gatstats#35]
Add option to include newsletter subscribers using https://www.gatsbyjs.org/packages/gatsby-plugin-mailchimp

Ideally the feature would not just handle the subscription form but also programmatically send the newsletter once a new post is published.

**Comment by PaulieScanlon** [comment]
Hey @maxscience i've just added a contact page to the demo. There's a few new components that are available via short codes in `.mdx` The demo uses Netlify forms but i think this could also work for your Newsletter requirements as all the theme needs to do is capture the data, after Netllify has it you should be able to what you want to it, pass it on to MailChimp for example. 

If you upgrade to `0.0.55` feel free to let me know what you think. 

I'll close this issue for now but if you have any further requests please raise and issue and i'll investigate!

Thanks
