### ISSUE TITLE
Side bar scroll bar issue 

### ISSUE THREAD

**Issue by PaulieScanlon** [PaulieScanlon/gatsby-theme-gatstats#36]
Chrome Win 10
https://twitter.com/damnitrahul/status/1227642427512512518?s=21

macOS 10.14.6 on Chrome Version 80.0.3987.87
https://twitter.com/mandamcneal/status/1228361718822080519
Amanda has suggested removing the `overflow-y: scroll`

**Comment by damnitrahul** [comment]
![image](https://user-images.githubusercontent.com/31034782/74365032-4cda7b80-4df3-11ea-96e6-79f3d34580e4.png)
Fullscreen screenshot for reference!

**Comment by PaulieScanlon** [comment]
![remove-over-flow-scroll-y](https://user-images.githubusercontent.com/1465706/74581519-4b1cdd80-4fd6-11ea-9d4b-d1b82422f47a.png)

**Comment by PaulieScanlon** [comment]
set `overflow-y:  auto` fixes this problem
